/*
 * Copyright (c) 2020 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define BT_MESH_DFD_OP_RECEIVERS_ADD BT_MESH_MODEL_OP_1(0x6F)
#define BT_MESH_DFD_OP_RECEIVERS_DELETE_ALL BT_MESH_MODEL_OP_2(0xB7, 0x20)
#define BT_MESH_DFD_OP_RECEIVERS_STATUS BT_MESH_MODEL_OP_2(0xB7, 0x21)
#define BT_MESH_DFD_OP_RECEIVERS_GET BT_MESH_MODEL_OP_2(0xB7, 0x22)
#define BT_MESH_DFD_OP_RECEIVERS_LIST BT_MESH_MODEL_OP_1(0x6E)
#define BT_MESH_DFD_OP_CAPABILITIES_GET BT_MESH_MODEL_OP_2(0xB7, 0x23)
#define BT_MESH_DFD_OP_CAPABILITIES_STATUS BT_MESH_MODEL_OP_1(0x6D)
#define BT_MESH_DFD_OP_GET BT_MESH_MODEL_OP_2(0xB7, 0x24)
#define BT_MESH_DFD_OP_START BT_MESH_MODEL_OP_1(0x6C)
#define BT_MESH_DFD_OP_CANCEL BT_MESH_MODEL_OP_2(0xB7, 0x25)
#define BT_MESH_DFD_OP_APPLY BT_MESH_MODEL_OP_2(0xB7, 0x26)
#define BT_MESH_DFD_OP_STATUS BT_MESH_MODEL_OP_1(0x6B)
#define BT_MESH_DFD_OP_UPLOAD_GET BT_MESH_MODEL_OP_2(0xB7, 0x27)
#define BT_MESH_DFD_OP_UPLOAD_START BT_MESH_MODEL_OP_1(0x6A)
#define BT_MESH_DFD_OP_UPLOAD_START_OOB BT_MESH_MODEL_OP_1(0x60)
#define BT_MESH_DFD_OP_UPLOAD_CANCEL BT_MESH_MODEL_OP_2(0xB7, 0x28)
#define BT_MESH_DFD_OP_UPLOAD_STATUS BT_MESH_MODEL_OP_1(0x5F)
#define BT_MESH_DFD_OP_FW_GET BT_MESH_MODEL_OP_1(0x5E)
#define BT_MESH_DFD_OP_FW_GET_BY_INDEX BT_MESH_MODEL_OP_2(0xB7, 0x29)
#define BT_MESH_DFD_OP_FW_DELETE BT_MESH_MODEL_OP_1(0x5D)
#define BT_MESH_DFD_OP_FW_DELETE_ALL BT_MESH_MODEL_OP_2(0xB7, 0x2A)
#define BT_MESH_DFD_OP_FW_STATUS BT_MESH_MODEL_OP_1(0x5C)
